# Generated by Django 6.0.1 on 2026-05-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_alter_whishlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whishlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
