# Generated by Django 6.0.1 on 2026-04-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='otpVerify',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
