# Generated by Django 6.0.1 on 2026-04-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodal',
            name='review',
        ),
    ]
